# Generated by Django 2.0.5 on 2018-05-21 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180521_1126'),
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktails',
            name='contains',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='image',
            field=models.ImageField(blank=True, upload_to='Cocktails_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='name',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='Название'),
        ),
    ]
