# Generated by Django 2.0.5 on 2018-05-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180521_1126'),
        ('cocktails', '0002_auto_20180521_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktails',
            name='contains',
        ),
        migrations.AddField(
            model_name='cocktails',
            name='contains',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='goods.Goods', verbose_name='Состав'),
        ),
    ]
