# Generated by Django 2.0.5 on 2018-05-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_auto_20180521_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktails',
            old_name='total',
            new_name='total_price',
        ),
    ]
