# Generated by Django 2.0.5 on 2018-05-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_auto_20180521_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktails',
            name='contains',
        ),
    ]
