# Generated by Django 2.0.5 on 2018-05-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена продажи (за 10мл)'),
        ),
    ]
