# Generated by Django 2.0.5 on 2018-05-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180521_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='in_stock',
            new_name='is_active',
        ),
    ]
