# Generated by Django 2.0.5 on 2018-05-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinorder',
            name='nmb',
            field=models.IntegerField(default=50, verbose_name='Количество (мл)'),
        ),
        migrations.AlterField(
            model_name='goodsinorder',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='goodsinorder',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за 50мл'),
        ),
        migrations.AlterField(
            model_name='goodsinorder',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='goodsinorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Всего'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Status', verbose_name='Статус'),
        ),
    ]
