# Generated by Django 2.0.5 on 2018-05-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180518_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinorder',
            name='nmb',
            field=models.IntegerField(default=10, verbose_name='Количество (мл)'),
        ),
    ]
